
spring:
  datasource:
    url: jdbc:mysql://bj-cdb-mw08tjgs.sql.tencentcdb.com:60042/javapub-flowable2?characterEncoding=UTF-8
    username: root
    password: 1234qwer
    driver-class-name: com.mysql.jdbc.Driver
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true
server:
  port: 8081
